name: quicktoast
description: "A simple and customizable toast/snackbar package for Flutter 🚀"
version: 0.0.1
homepage: https://github.com/YOUR_GITHUB/quicktoast

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # assets aur fonts abhi zaroori nahi, agar chaho to baad me add kar sakte ho
