name: quicktoast
description: Can called modiefied widgets like , loaders, toast, quick button, camera widgets
version: 0.0.1
homepage: https://github.com/DevBeastTeam/quick_widget_package
repository: https://github.com/DevBeastTeam/quick_widget_package
issue_tracker: https://github.com/DevBeastTeam/quick_widget_package/issues
documentation: https://github.com/DevBeastTeam/quick_widget_package#readme

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
