name: quicktoast
description: A simple and customizable toast/snackbar package for Flutter 🚀
version: 0.0.1
homepage: https://github.com/DevBeastTeam/quick_widget_package
repository: https://github.com/DevBeastTeam/quick_widget_package
issue_tracker: https://github.com/DevBeastTeam/quick_widget_package/issues
documentation: https://github.com/DevBeastTeam/quick_widget_package#readme

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
